# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 0
# Issues with these labels will never be considered stale
exemptLabels:
  - improvement
  - not-completed
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Your coursework submission has been closed because nobody has interacted with it in 30 days. You are welcome to re-open it to get more feedback.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
