name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '* * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          close-pr-message: 'Your coursework submission has been closed because nobody has interacted with it in 30 days. You are welcome to re-open it to get more feedback.'
          days-before-stale: -1
          days-before-close: 30
          days-before-issue-close: -1
