# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Homework Completed

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      logs: ${{ steps.run.outputs.logs }}
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Code 
      id: run
      run: echo "::set-output name=logs::$(node mandatory/1-syntax-errors.js)\n"
      continue-on-error: true
  job2:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - run: echo ${{needs.build.outputs.logs}}
  comment:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: Result ${{ needs.build.outputs.logs }}
