name: Homework Completed

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      logs: ${{ steps.run.outputs.logs }}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Code 
      id: run
      run: |
        # run command and capture stderr
        node mandatory/1-syntax-errors.js 2> logs.txt
        echo ::set-output name=logs::`cat logs.txt`
        # run again to get exit code
        node mandatory/1-syntax-errors.js
      continue-on-error: true
  job2:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - run: echo ${{needs.build.outputs.logs}}
  comment:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: Result ${{ needs.build.outputs.logs }}
